_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  ROI_MASK_HEAD:
    LOSS: "bce"
    USE_COORD_CONV: false
  ROI_HEADS:
    NMS_TYPE: "default"
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
